import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Stack } from '@mui/material';
import { colorPallete } from './utils/colorspallete';
import Navbar from './components/Navbar';
import QueryProvider from './components/QueryProvider';
import { AuthProvider } from './provider/auth-provider/authProvider';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<QueryProvider>
					<AuthProvider>
						<Stack
							bgcolor={colorPallete['low-grey']}
							color={colorPallete.black}
							position={'relative'}
							minHeight={'100vh'}>
							<Navbar />
							{children}
						</Stack>
					</AuthProvider>
				</QueryProvider>
			</body>
		</html>
	);
}
